src/IterationWebApp/Controllers/QuestionTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using IterationWebApp.ViewModels;
using IterationWebApp.Models;
using Microsoft.AspNet.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace IterationWebApp.Controllers
{
    [Authorize]
    [RequireHttps]
    public class QuestionTypesController : Controller
    {
        private IIterationRepository _repository;

        public QuestionTypesController(IIterationRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var types = _repository.GetAllQuestionTypes();
            return View(types);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateQuestionTypeViewModel());
        }

        [HttpPost][ValidateAntiForgeryToken]
        public  IActionResult Create(CreateQuestionTypeViewModel vmQuestionType)
        {
            if (!ModelState.IsValid)
            {
                return View(vmQuestionType);
            }
            _repository.AddQuestionType(vmQuestionType);
             //TempData["Msg"] = vmQuestionType.Question_Type + " Added Successfully";
            return RedirectToAction("Create","Questions");
        }

       
        public IActionResult Delete(long? id)
        {
            _repository.DeleteQuestionType(id);
            return View();
        }
    }
}

src/IterationWebApp/Views/QuestionTypes/Create.cshtml
@model CreateQuestionTypeViewModel

@{
    Layout = null;

}
@*@{
   
    await Html.RenderPartialAsync("_AddQuestionType", Model);
}*@

src/IterationWebApp/Views/QuestionTypes/Delete.cshtml
<h3 class="text-success">Deleted Successfully!</h3>
<a asp-action="Index" asp-controller="QuestionTypes" class="btn btn-sm btn-success">Back To List</a>

src/IterationWebApp/Views/QuestionTypes/Index.cshtml
@model IEnumerable<QuestionType>
<div class="row">
    <div class="col-md-4">
        <p class="text-left page-header text-uppercase" style="font-size:28px;">Question Types  <a data-toggle="modal" data-target="#CreateQtype" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-plus"></i> Add Question Type</a></p>
        
    </div>
    
</div>
    <div class="list-group col-md-6">
        @foreach (var item in Model)
        {
            <div class="list-group-item col-md-3">@item.Question_Type</div>

            <div class="list-group-item col-md-1">

                <a asp-action="Delete" asp-controller="QuestionTypes" asp-route-id="@item.Question_Type_Id" class="text-center"><i class="glyphicon glyphicon-trash"></i></a>

            </div>


        }
    </div>

<div class="modal fade" id="CreateQtype" tabindex="-1" role="dialog" aria-labelledby="createQtype" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="createQtype">Add Question Type</h4>
            </div>
            <div class="modal-body">

                @{
                    await Html.RenderPartialAsync("_AddQuestionType", new CreateQuestionTypeViewModel());
                }

            </div>
        </div>
    </div>
</div>