src/IterationWebApp/Models/Procurement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace IterationWebApp.Models
{
    public class Procurement 
    {
        [Key]
        public long Procurement_Id { get; set; }

        public string Service_Procured { get; set; }

        
        public  DateTime? Date_Of_Submission { get; set; }

        public string PublishedDate { get; set; }

        public string Response_Evaluation { get; set; }

        public string Note { get; set; }

        public DateTime? ModifiedDate { get; set; }

        public long CompanyID { get; set; }

        public virtual Company Company { get; set; }

        //public virtual Question question{ get; set; }

        //public ICollection<Company> Companies { get; set; }
        public ICollection<Question> Questions { get; set; }





    }
}

src/IterationWebApp/Controllers/ProcurementsController.cs
using System;
using Microsoft.AspNet.Mvc;
using IterationWebApp.Models;
using IterationWebApp.ViewModels;
using Microsoft.AspNet.Authorization;
using System.Linq;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using System.Net;

namespace IterationWebApp.Controllers
{
    [Authorize]
    [RequireHttps]
    public class ProcurementsController : Controller
    {
        private IIterationRepository _repository;

        //Constructor
        public ProcurementsController(IIterationRepository repository)
        {
            _repository = repository;
        }

        #region Index Action Method for Procurement
        //Index Method for Procurement 
        public IActionResult Index(string keyword, string keyword2, string keyword3, DateTime? datetimepicker2, string SortOrder, string SortBy, string Page)
        {

            var procurements = _repository.GetAllProcurement();

            #region Sorting section
            switch (SortBy)
            {
                case "Company_Name":
                    switch (SortOrder)
                    {
                        case "Asc":
                            procurements = _repository.GetAllProcurementOrderByCompanyName();
                            break;
                        case "Desc":
                            procurements = _repository.GetAllProcurementOrderByDesc();
                            break;
                        default:
                            break;

                    }
                    break;
                case "Service_Procured":
                    switch (SortOrder)
                    {
                        case "Asc":
                            procurements = _repository.GetAllProcurementOrderByServiceProcured();
                            break;
                        case "Desc":
                            procurements = _repository.GetAllProcurementDescByServiceProcured();
                            break;
                        default:
                            break;

                    }
                    break;
                case "Response_Evaluation":
                    switch (SortOrder)
                    {
                        case "Asc":
                            procurements = _repository.GetAllProcurementOrderByResEval();
                            break;
                        case "Desc":
                            procurements = _repository.GetAllProcurementDescByResEval();
                            break;
                        default:
                            break;

                    }
                    break;
                case "Date_Of_Submission":
                    switch (SortOrder)
                    {
                        case "Asc":
                            procurements = _repository.GetAllProcurementOrderByResEval();
                            break;
                        case "Desc":
                            procurements = _repository.GetAllProcurementDescByResEval();
                            break;
                        default:
                            break;

                    }
                    break;

            }
            #endregion

            #region Search Functions
            //search by procurements
            if (!String.IsNullOrEmpty(keyword) && String.IsNullOrEmpty(keyword2) && datetimepicker2 == null && String.IsNullOrEmpty(keyword3))
            {
                procurements = _repository.GetSpecificProcurement(keyword);


            }
            //search by company
            if (!String.IsNullOrEmpty(keyword2) && String.IsNullOrEmpty(keyword) && datetimepicker2 == null && String.IsNullOrEmpty(keyword3))
            {
                procurements = _repository.GetSpecificProcurementByCompany(keyword2);
                //TempData["error"] = "Matching records not found!";
            }

            //search by response
            if (!String.IsNullOrEmpty(keyword3) && String.IsNullOrEmpty(keyword) && String.IsNullOrEmpty(keyword2) && datetimepicker2 == null)
            {
                procurements = _repository.GetSpecificProcurementByResponse(keyword3);

            }

            if (datetimepicker2 != null && String.IsNullOrEmpty(keyword3) && String.IsNullOrEmpty(keyword) && String.IsNullOrEmpty(keyword2))
            {
                procurements = _repository.GetSpecificProcurementByDate(datetimepicker2);
            }


            #endregion

            #region Pagination Section
            var pageSize = 4;
            var Total = _repository.GetTotalProcurements();


            ViewBag.SortOrder = SortOrder;
            ViewBag.SortBy = SortBy;

            ViewBag.TotalPages = Math.Ceiling(Total / pageSize);

            int page = int.Parse(Page == null ? "1" : Page);
            ViewBag.Page = page;

            var previousPage = page - 1;
            var nextPage = page + 1;

            ViewBag.PreviousPage = previousPage;
            ViewBag.HasPreviousPage = previousPage > 0;
            ViewBag.NextPage = nextPage;
            ViewBag.HasNextPage = nextPage < ViewBag.TotalPages;

            procurements = procurements.Skip((page - 1) * pageSize).Take(10);
            #endregion
            return View(procurements);
        }
        #endregion

        #region Create Procurement
        public IActionResult Create()
        {
            var viewModel = _repository.LoadCompanies(new CreateProcurementViewModel());
            return View(viewModel);
        }


        //Create Procurements
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateProcurementViewModel vmProcurement)
        {
            if (!ModelState.IsValid)
            {
                return View(vmProcurement);
            }

            _repository.AddProcurement(vmProcurement);
            TempData["success"] = vmProcurement.Service_Procured + " is added successfully!";
            return RedirectToAction("Index");
        }
        #endregion

        #region Detail Action method
        //Details
        public IActionResult Detail(long id)
        {

            var procurement = _repository.GetProcurementById(id);


            // return ViewComponent("ProcurementDetail", procurement.Procurement_Id);
            return View(procurement);
        }

        #endregion
        #region Delete Procurement
        //Delete 
        public IActionResult DeleteProcurement(long? id)
        {
            //_repository.DeleteProcurement(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(400);
            }
            Procurement pro = _repository.GetByID(id);
            if (pro == null)
            {
                return HttpNotFound();
            }

            return View(pro);
        }

        //Confirm Delete
        [HttpPost]
        [ActionName("DeleteProcurement")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmation(long id)
        {
            _repository.DeleteProcurement(id);
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region Edit Procurement
        //Edit Action for Procurement
        public IActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(400);
            }

            EditProcurementViewModel vmPro = _repository.Edit(id);
            if (vmPro == null)
            {
                return HttpNotFound();
            }

            _repository.LoadCompaniesToEdit(vmPro);
            return View(vmPro);
        }


        //Edit post action for procurement
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Procurement Pro)
        {

            if (!ModelState.IsValid)
                return View(Pro);

            _repository.UpdateProcurement(Pro);
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

src/IterationWebApp/Views/Procurements/Create.cshtml
@model CreateProcurementViewModel

@{
    ViewBag.Title = "Iteration AB - Add Procurement";
}

@*<div class="row button-nav">
        <div class="col-md-1">
            <a asp-action="Index" asp-controller="Home" class="btn btn-sm btn-primary">Back</a>
        </div>

    </div>*@

<div class="col-sm-12">
    <div class="col-md-2 col-sm-offset-2">
        <h2 class="text-capitalize">Add Procurement</h2>
    </div>
</div>


<div class="col-sm-12">
    <form asp-controller="Procurements" asp-action="Create" class="form-horizontal" asp-antiforgery="true">

        <div class="form-group">

            <label asp-for="Service_Procured" class="col-sm-2 control-label"></label>
            <div class="col-sm-3">
                <input asp-for="Service_Procured" class="form-control" />
                <span asp-validation-for="Service_Procured" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Response_Evaluation" class="col-sm-2 control-label"></label>
            <div class="col-sm-3">
                <input asp-for="Response_Evaluation" class="form-control" />
                <span asp-validation-for="Response_Evaluation" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Note" class="col-sm-2 control-label"></label>
            <div class="col-sm-3">
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
        </div>
        @*<div class="form-group">
                <label asp-for="Company.Company_Name" class="col-sm-2 control-label"></label>
                <div class="col-sm-3">
                    <input asp-for="Company.Company_Name" class="form-control" />
                    <input type="hidden" asp-for="Company.Company_Id" />
                    <span asp-validation-for="Company.Company_Name" class="text-danger"></span>
                </div>
            </div>*@

        <div class="form-group">
            <label asp-for="SelectedCompanyID" class="col-sm-2 control-label"></label>
            <div class="col-sm-3">
                <select asp-for="SelectedCompanyID" class="form-control" asp-items="Model.Companies">
                    <option id="select" value="">Select Company</option>

                </select>

                <span asp-validation-for="SelectedCompanyID" class="text-danger"></span>
            </div>
            <div class="col-sm-3">
                <a data-toggle="modal" data-target="#CreateCompany" class="btn btn-success">Add Company</a>
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Add" class="btn btn-success" />
            </div>
        </div>
    </form>
</div><!--end of row-->

<div class="modal fade" id="CreateCompany" tabindex="-1" role="dialog" aria-labelledby="createCompany" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="createCompany">Add Company</h4>
            </div>
            <div class="modal-body">

                @{
                    await Html.RenderPartialAsync("_AddCompany", new CreateCompanyViewModel());
                }
                
            </div>
        </div>
    </div>
</div>

src/IterationWebApp/Views/Procurements/DeleteProcurement.cshtml
@model Procurement
@{
    Layout = null;
}

@{
    ViewBag.Title = "Delete";
}

@{
    await Html.RenderPartialAsync("_DeleteProcurement", Model);
}

src/IterationWebApp/Views/Procurements/Detail.cshtml
@model DisplayProcurementViewModel
@{
    ViewBag.Title = "Iteration AB - Procurement Details";
}
<div class="row">
    <div class="col-md-4">

        <h2 class="page-header">Procurement Details</h2>
    </div>

</div>
<div class="row">
    <div class="col-md-6">
        <div class="row detail_records">

            <div class="col-md-3 text-right text-success"><strong>Procurement:</strong></div>
            <div class="col-md-3 text-left">@Model.Service_Procured</div>
        </div>
        <div class="row detail_records">
            <div class="col-md-3 text-right text-success"><strong> Evaluation:</strong></div>
            <div class="col-md-3 text-left">@Model.Response_Evaluation</div>
        </div>
        <div class="row detail_records">
            <div class="col-md-3 text-right text-success"><strong>Date of Submission:</strong></div>
            <div class="col-md-3 text-left">@Model.Date_Of_Submission</div>
        </div>
        <div class="row detail_records">
            <div class="col-md-3 text-right text-success"><strong>Company:</strong></div>
            <div class="col-md-3 text-left">@Model.CompanyName</div>
        </div>
        <div class="row detail_records">
            <div class="col-md-3 text-right text-success"><strong>Note:</strong></div>
            <div class="col-md-3 text-left">@Model.Note</div>
        </div>
    </div>

    <div class="col-md-6 pull-right">
        @foreach (var item in Model.Questions)
            {
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="Qload">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#@item.Question_Id" aria-expanded="true" aria-controls="Qcol">
                                View Question No. @item.Question_Number
                            </a>
                        </h4>
                    </div>
                    <div id="@item.Question_Id" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="Qload">
                        <div class="panel-body">
                            <ul class="list-group">
                                <li class="list-group-item">
                                    <strong>Question: <span class="text-success">@item.question</span></strong>
                                </li>
                                <li class="list-group-item">
                                    <strong>Question Type: <span class="text-success">@item.QuestionType.Question_Type</span></strong>
                                </li>


                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        }


    </div>



</div>
<div class="row">

</div>

src/IterationWebApp/Views/Procurements/Edit.cshtml
@model EditProcurementViewModel
@{
    Layout = null;
    ViewBag.Title = "Iteration AB - Procurement Edit";
}


@{
    await Html.RenderPartialAsync("_EditProcurement", Model);
}

src/IterationWebApp/Views/Procurements/Index.cshtml
@model IEnumerable<Procurement>

@{
    ViewBag.Title = "Iteration AB - Procurements";
}

@*@model List<DisplayProcurementViewModel>*@
<div class="row">
    <div class="col-sm-4">
        
        @*@Html.ActionLink("PDF", "ExportTo", new { ReportType ="PDF"})
            @Html.ActionLink("Excel", "ExportTo", new { ReportType = "Excel"})*@
        <p class="page-header text-uppercase" style="font-size:28px;">Procurements   <a asp-controller="Procurements" asp-action="Create" class="btn btn-sm btn-danger"><i class="fa fa-plus"></i> Add Procurement</a></p>
        
    </div>
   


</div>
<div class="row">
    <div class="col-md-6">
        @if (TempData["success"] != null)
        {   <script>
            $(document).ready(function () {

                alert('@TempData["success"]');

            });

            </script>
            @*<p class="text-success">@TempData["success"]</p>*@

        }
    </div>

</div>
<!--starts search forms-->
<div class="row" style="padding-bottom:20px;">

    <div class="col-sm-3">
        <form asp-controller="Procurements" asp-action="Index" method="get" class="form-inline" role="search">

            <!--search by company-->
            <div class="input-group form-group">
                <input type="text" placeholder="company name" name="keyword2" class="form-control" size="20" />
                <span name="keyword2"></span>


            </div>
            <div class="input-group">
                <input name="keyword2" type="submit" value="Search By Company" class="btn btn-sm btn-success" />
            </div>
        </form>
    </div>

    <div class="col-sm-3">
        <!--Search By Service Procured-->
        <form asp-controller="Procurements" asp-action="Index" method="get" class="form-inline" role="search">
            <!--search by procurement-->
            <div class="input-group form-group">
                <input type="text" placeholder="service procured" name="keyword" class="form-control" size="20" />

                <span name="keyword"></span>


            </div>
            <div class="input-group">
                <input name="keyword" type="submit" value="Search By Procurement" class="btn btn-sm btn-success" />
            </div>

        </form>
    </div>



    <div class="col-sm-3">
        <form asp-controller="Procurements" asp-action="Index" method="get" class="form-inline" role="search">
            <!--search by response-->
            <div class="input-group form-group">
                <input type="text" placeholder="Response" name="keyword3" class="form-control" size="20" />
                <span name="keyword3"></span>


            </div>
            <div class="input-group">
                <input type="submit" value="Search By Response" class="btn btn-sm btn-success" />
            </div>
        </form>
    </div>

    <div class="col-sm-3">
        <form asp-controller="Procurements" asp-action="Index" method="get" class="form-inline" role="search">
            <!--DateTime Picker filter-->
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <input type='text' class="form-control" placeholder="Search by Date and time" name="datetimepicker2" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="input-group">
                <input type="submit" value="Search By Date" class="btn btn-sm btn-success" />
            </div>
        </form>
    </div>
    @if (TempData["error"] != null)
    {
        <p class="text-danger">@TempData["error"]</p>
    }
</div><!--end row-->

<!--end of search forms-->
<!--Starts Procurements List Table-->
<div class="container-fluid">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Procured services by company</div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped">
                    <thead>
                        <tr>
                            <th>

                                @Html.ActionLink("Company Name", "Index", new { SortOrder = (ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc")), SortBy = "Company_Name", Page = (ViewBag.Page == null ? "1" : ViewBag.Page) })
                                @if (ViewBag.SortOrder == null || ViewBag.SortBy == "Service_Procured" || ViewBag.SortBy == "Response_Evaluation" || ViewBag.SortBy == "Date_Of_Submission")
                                {
                                    <i class="glyphicon glyphicon-sort"></i>
                                }

                                @if (ViewBag.SortOrder == "Asc" && ViewBag.SortBy == "Company_Name")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                                @if (ViewBag.SortOrder == "Desc" && ViewBag.SortBy == "Company_Name")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet-alt" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                            </th>

                            <th>
                                @Html.ActionLink("Service Procured", "Index", new { SortOrder = (ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc")), SortBy = "Service_Procured", Page = (ViewBag.Page == null ? "1" : ViewBag.Page) })
                                @if (ViewBag.SortOrder == null || ViewBag.SortBy == "Company_Name" || ViewBag.SortBy == "Response_Evaluation" || ViewBag.SortBy == "Date_Of_Submission")
                                {
                                    <i class="glyphicon glyphicon-sort"></i>
                                }

                                @if (ViewBag.SortOrder == "Asc" && ViewBag.SortBy == "Service_Procured")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                                @if (ViewBag.SortOrder == "Desc" && ViewBag.SortBy == "Service_Procured")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet-alt" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }



                            </th>
                            <th class="visible-lg">
                                @Html.ActionLink("Response Evaluation", "Index", new { SortOrder = (ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc")), SortBy = "Response_Evaluation", Page = (ViewBag.Page == null ? "1" : ViewBag.Page) })
                                @if (ViewBag.SortOrder == null || ViewBag.SortBy == "Company_Name" || ViewBag.SortBy == "Service_Procured" || ViewBag.SortBy == "Date_Of_Submission")
                                {
                                    <i class="glyphicon glyphicon-sort"></i>
                                }

                                @if (ViewBag.SortOrder == "Asc" && ViewBag.SortBy == "Response_Evaluation")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                                @if (ViewBag.SortOrder == "Desc" && ViewBag.SortBy == "Response_Evaluation")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet-alt" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                            </th>
                            <th class="visible-lg">
                                @Html.ActionLink("Date Of Submission", "Index", new { SortOrder = (ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc")), SortBy = "Date_Of_Submission", Page = (ViewBag.Page == null ? "1" : ViewBag.Page) })
                                @if (ViewBag.SortOrder == null || ViewBag.SortBy == "Company_Name" || ViewBag.SortBy == "Service_Procured" || ViewBag.SortBy == "Response_Evaluation")
                                {
                                    <i class="glyphicon glyphicon-sort"></i>
                                }

                                @if (ViewBag.SortOrder == "Asc" && ViewBag.SortBy == "Date_Of_Submission")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                                @if (ViewBag.SortOrder == "Desc" && ViewBag.SortBy == "Date_Of_Submission")
                                {
                                    <i class="glyphicon glyphicon-sort-by-alphabet-alt" style="color:red"></i>
                                    @*<i class="glyphicon glyphicon-sort hidden"></i>*@
                                }
                            </th>
                            <th>
                                
                                <a href="#">Modified Date</a>
                            </th>
                            <th class="visible-lg"><a>Note</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Company.Company_Name</td>
                                <td>@item.Service_Procured</td>
                                <td class="visible-lg">@item.Response_Evaluation</td>
                                <td class="visible-lg">@item.PublishedDate</td>
                                <td class="visible-lg">@item.ModifiedDate</td>
                                <td class="visible-lg"><p class="bg-info text-justify text-center">@item.Note</p></td>
                                

                            </tr>

                        }
                    </tbody>


                </table>

            </div>

        </div>
    </div><!--end of row-->
    <!--Pagination Starts-->
    <nav>
        <ul class="pagination">
            <li>
                @if (ViewBag.HasPreviousPage == true)
                {

                    <a href="@Url.Action("Index", new {Page = ViewBag.PreviousPage })" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                }


            </li>
            @{
                double totalPages = ViewBag.TotalPages;

            }
            @for (int i = 1; i < totalPages; i++)
            {

                <li>@Html.ActionLink(i.ToString() + " ", "Index", new { SortOrder = (ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder), SortBy = (ViewBag.SortBy == null ? "Company_Name" : ViewBag.SortBy), Page = i })</li>


            }

            <li>
                @if (ViewBag.HasNextPage == true)
                {
                    <a href="@Url.Action("Index", new {Page = ViewBag.NextPage })" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                }
            </li>
        </ul>
    </nav>


</div>
<!--End Procurements List Table-->